### ISSUE TITLE
npm run test script should not run once

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/simple-todos#4]
The [tutorial step 11](https://github.com/jankapunkt/simple-todos/blob/tortilla/.tortilla/manuals/views/step11.md) contains the following code for running the tests:

```bash
TEST_WATCH=1 meteor test --driver-package meteortesting:mocha
```

However, the npm test script is running using `--once`:

```json
{
  "scripts": {
    "test": "meteor test --once --driver-package meteortesting:mocha"
  }
}
```

We should add the above line to `scripts` as  `test-watch`, so the project when download provides the same functionality as mentioned in the tutorials.

**Comment by harryadelb** [comment]
We've got the test-app command which does this:
```
"test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha"
```
